# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(681, 749)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.viewer = QtGui.QLabel(self.centralwidget)
        self.viewer.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.viewer.setFrameShape(QtGui.QFrame.Box)
        self.viewer.setText(_fromUtf8(""))
        self.viewer.setScaledContents(False)
        self.viewer.setAlignment(QtCore.Qt.AlignCenter)
        self.viewer.setObjectName(_fromUtf8("viewer"))
        self.btn_verify = QtGui.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(260, 590, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_verify.setFont(font)
        self.btn_verify.setObjectName(_fromUtf8("btn_verify"))
        self.btn_takePhoto = QtGui.QPushButton(self.centralwidget)
        self.btn_takePhoto.setGeometry(QtCore.QRect(20, 520, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_takePhoto.setFont(font)
        self.btn_takePhoto.setObjectName(_fromUtf8("btn_takePhoto"))
        self.btn_openLink = QtGui.QPushButton(self.centralwidget)
        self.btn_openLink.setGeometry(QtCore.QRect(20, 660, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_openLink.setFont(font)
        self.btn_openLink.setObjectName(_fromUtf8("btn_openLink"))
        self.btn_clear = QtGui.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(240, 520, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.btn_ok = QtGui.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(150, 520, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_ok.setFont(font)
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.btn_quit = QtGui.QPushButton(self.centralwidget)
        self.btn_quit.setGeometry(QtCore.QRect(550, 670, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_quit.setFont(font)
        self.btn_quit.setObjectName(_fromUtf8("btn_quit"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 600, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 590, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 660, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_status = QtGui.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(210, 660, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_status.setFont(font)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.btn_home = QtGui.QPushButton(self.centralwidget)
        self.btn_home.setGeometry(QtCore.QRect(580, 590, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_home.setFont(font)
        self.btn_home.setObjectName(_fromUtf8("btn_home"))
        self.btn_point = QtGui.QPushButton(self.centralwidget)
        self.btn_point.setGeometry(QtCore.QRect(390, 590, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_point.setFont(font)
        self.btn_point.setObjectName(_fromUtf8("btn_point"))
        self.pos_x = QtGui.QLineEdit(self.centralwidget)
        self.pos_x.setGeometry(QtCore.QRect(410, 540, 51, 27))
        self.pos_x.setObjectName(_fromUtf8("pos_x"))
        self.pos_y = QtGui.QLineEdit(self.centralwidget)
        self.pos_y.setGeometry(QtCore.QRect(500, 540, 51, 27))
        self.pos_y.setObjectName(_fromUtf8("pos_y"))
        self.pos_h = QtGui.QLineEdit(self.centralwidget)
        self.pos_h.setGeometry(QtCore.QRect(590, 540, 51, 27))
        self.pos_h.setObjectName(_fromUtf8("pos_h"))
        self.label_x = QtGui.QLabel(self.centralwidget)
        self.label_x.setGeometry(QtCore.QRect(390, 530, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_x.setFont(font)
        self.label_x.setObjectName(_fromUtf8("label_x"))
        self.label_y = QtGui.QLabel(self.centralwidget)
        self.label_y.setGeometry(QtCore.QRect(480, 530, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_y.setFont(font)
        self.label_y.setObjectName(_fromUtf8("label_y"))
        self.label_h = QtGui.QLabel(self.centralwidget)
        self.label_h.setGeometry(QtCore.QRect(570, 530, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_h.setFont(font)
        self.label_h.setObjectName(_fromUtf8("label_h"))
        self.btn_cancel = QtGui.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(490, 590, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AGV", None))
        self.btn_verify.setText(_translate("MainWindow", "Verify", None))
        self.btn_takePhoto.setText(_translate("MainWindow", "Take Photo", None))
        self.btn_openLink.setText(_translate("MainWindow", "Open Link", None))
        self.btn_clear.setText(_translate("MainWindow", "Clear", None))
        self.btn_ok.setText(_translate("MainWindow", "OK", None))
        self.btn_quit.setText(_translate("MainWindow", "Quit", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "<choose>", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Robin_Lin", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Max_Huang", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "Daniel_Lin", None))
        self.label.setText(_translate("MainWindow", "Choose user: ", None))
        self.label_2.setText(_translate("MainWindow", "Status:", None))
        self.label_status.setText(_translate("MainWindow", "Unauthorized", None))
        self.btn_home.setText(_translate("MainWindow", "Home", None))
        self.btn_point.setText(_translate("MainWindow", "Point", None))
        self.pos_x.setText(_translate("MainWindow", "0", None))
        self.pos_y.setText(_translate("MainWindow", "0", None))
        self.pos_h.setText(_translate("MainWindow", "0", None))
        self.label_x.setText(_translate("MainWindow", "x:", None))
        self.label_y.setText(_translate("MainWindow", "y:", None))
        self.label_h.setText(_translate("MainWindow", "h:", None))
        self.btn_cancel.setText(_translate("MainWindow", "Cancel", None))

